
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LAB2(

	//////////// SEG7 //////////
	
	output			  [9:0]		LEDR,
	output				zeroseg,
	//////////// SW //////////
	
	input					X3,
	input					X2,
	input					X1,
	input					X0
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

//supresses LEDR, not needed, but handy.
assign LEDR[9:0] = 1'b0;
assign zeroseg = ~(X3 & X2 & X1 & X0);
//If wanting to do the opposite, set zeroseg = X3 & X2 & X1 & X0

endmodule
