
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LAB5(

	//////////// CLOCK //////////
	//input 		          		ADC_CLK_10,
	//input 		          		MAX10_CLK1_50,
	//input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		reg     [6:0]		HEX0,
	output		reg     [6:0]		HEX1,

	//////////// KEY //////////
	
	input async_reset, //KEY 1
	input keyclk, //KEY 0

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [7:0]		SW,
	output reg [7:0] result
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

reg [3:0] res0, res1;


//=======================================================
//  Structural coding
//=======================================================

assign LEDR[9:0] = 1'b0;
always @(*)

	
	
	begin
	
	
			
		if(async_reset==1'b1 && keyclk==1'b0) begin
				result <= SW;
				{res1,res0} = result;
		end else if (async_reset==1'b0 && keyclk==1'b1)begin 
				result <= 8'b00000000;
			{res1,res0} = result;	
			end
			
			case({res0})
	
				4'b0000: HEX0 = 7'b1000000;//Blank
				4'b0001:	HEX0 = 7'b1111001;//1
				4'b0010:	HEX0 = 7'b0100100;//2
				4'b0011:	HEX0 = 7'b0110000;//3
				4'b0100: HEX0 = 7'b0011001;//4		
				4'b0101: HEX0 = 7'b0010010;//5		
				4'b0110: HEX0 = 7'b0000010;//6
				4'b0111: HEX0 = 7'b1111000;//7
				4'b1000: HEX0 = 7'b0000000;//8
				4'b1001: HEX0 = 7'b0010000;//9
				4'b1010: HEX0 = 7'b0001000;//A
				4'b1011: HEX0 = 7'b0000011;//b
				4'b1100: HEX0 = 7'b1000110;//C
				4'b1101: HEX0 = 7'b0100001;//d
				4'b1110: HEX0 = 7'b0000110;//E
				4'b1111: HEX0 = 7'b0001110;//F
				
			endcase
	
			case({res1})
	
				4'b0000: HEX1 = 7'b1000000;//Blank
				4'b0001:	HEX1 = 7'b1111001;//1
				4'b0010:	HEX1 = 7'b0100100;//2
				4'b0011:	HEX1 = 7'b0110000;//3
				4'b0100: HEX1 = 7'b0011001;//4		
				4'b0101: HEX1 = 7'b0010010;//5		
				4'b0110: HEX1 = 7'b0000010;//6
				4'b0111: HEX1 = 7'b1111000;//7
				4'b1000: HEX1 = 7'b0000000;//8
				4'b1001: HEX1 = 7'b0010000;//9
				4'b1010: HEX1 = 7'b0001000;//A
				4'b1011: HEX1 = 7'b0000011;//b
				4'b1100: HEX1 = 7'b1000110;//C
				4'b1101: HEX1 = 7'b0100001;//d
				4'b1110: HEX1 = 7'b0000110;//E
				4'b1111: HEX1 = 7'b0001110;//F
				
			endcase
			
		//posedge keyclk or posedge async_reset
	
	end
endmodule
