
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LAB1(

	//////////// KEY //////////
	input 		     [1:0]		KEY,
	input					Internal,
	input					External,
	input					Fire_alarm,

	//////////// LED //////////
	output		     [9:1]		LEDR,
	output				Door_op,

	//////////// SW //////////
	input 		     [9:1]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

//assign LEDR[9:1] = 1'b0;

assign Door_op = (~Internal & Fire_alarm) | (~Internal & External);

endmodule
